name: CI

on:
  push:
    branches: [ "github_actions" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pytest1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests with pytest
        run: pytest
        
  merge_main:
    needs: pytest1 # code taken from https://stackoverflow.com/questions/62750603/github-actions-trigger-another-action-after-one-action-is-completed
    runs-on: ubuntu-latest
    steps:
      - name: git repo checkout
        uses: actions/checkout@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
# Code taken from https://www.jessesquires.com/blog/2022/03/26/gh-action-merge-release-to-main/
      - name: Create pull request
        id: open-pr
        uses: repo-sync/pull-request@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          destination_branch: ${{ github.event.repository.default_branch }}
          pr_title: "[Automated] Merge ${{ github.ref_name }} into ${{ github.event.repository.default_branch }}"
          pr_body: "Automated Pull Request"
          pr_reviewer: "raghurajshetty"
          pr_assignee: "raghurajshetty"
          
      #- name: Merge Pull request to main
      #  if: steps.open-pr.outputs.pr_number != ''
      #  uses: peter-evans/enable-pull-request-automerge@v2
      #  with:
      #   token: ${{ secrets.GITHUB_TOKEN }}
      #    pull-request-number: ${{ steps.open-pr.outputs.pr_number }}
      #    merge-method: merge
